In [5]:
import pandas as pd

CCTV_seoul = pd.read_csv("/content/drive/MyDrive/data/DataScience-master/DataScience-master/data/01. CCTV_in_Seoul.csv")
## 하위 5개
#CCTV_seoul.sort_values(by="소계",ascending=True).head(5)
## 상위 5개
CCTV_seoul.sort_values(by="소계",ascending=False).head(5)

    기관명    소계  2013년도 이전  2014년  2015년  2016년
0   강남구  2780       1292    430    584    932
18  양천구  2034       1843    142     30    467
14  서초구  1930       1406    157    336    398
21  은평구  1873       1138    224    278    468
20  용산구  1624       1368    218    112    398

In [6]:
## CCTV 증가율 확인
CCTV_seoul["최근증가율"] = (CCTV_seoul['2016년']+CCTV_seoul['2015년']+CCTV_seoul['2014년'])/CCTV_seoul['2013년도 이전'] * 100
CCTV_seoul.sort_values(by="최근증가율",ascending=False).head(5)

    기관명    소계  2013년도 이전  2014년  2015년  2016년       최근증가율
22  종로구  1002        464    314    211    630  248.922414
9   도봉구   485        238    159     42    386  246.638655
12  마포구   574        314    118    169    379  212.101911
8   노원구  1265        542     57    451    516  188.929889
1   강동구   773        379     99    155    377  166.490765

In [22]:
Popular_seoul = pd.read_excel("/content/drive/MyDrive/data/DataScience-master/DataScience-master/data/01. population_in_Seoul.xls",
                              header=2, usecols="B, D, G, J, N")

Popular_seoul.rename(columns={Popular_seoul.columns[0]:"구별",
                              Popular_seoul.columns[1]:"인구수",
                              Popular_seoul.columns[2]:"한국인",
                              Popular_seoul.columns[3]:"외국인",
                              Popular_seoul.columns[4]:"고령자"}, inplace=True)
Popular_seoul.head()

    구별         인구수        한국인       외국인        고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [25]:
# drop
Popular_seoul.drop(0, inplace=True)
Popular_seoul.head()

    구별       인구수       한국인      외국인      고령자
1  종로구  162820.0  153589.0   9231.0  25425.0
2   중구  133240.0  124312.0   8928.0  20764.0
3  용산구  244203.0  229456.0  14747.0  36231.0
4  성동구  311244.0  303380.0   7864.0  39997.0
5  광진구  372164.0  357211.0  14953.0  42214.0

In [27]:
## 각 행이 가지는 종류 출력
Popular_seoul['구별'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', nan],
      dtype=object)

In [28]:
## 어디가 NaN값을 가지는지 찾기
Popular_seoul['구별'].isnull()

1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
Name: 구별, dtype: bool

In [29]:
## NaN값 가지는 행의 다른 값들 확인
Popular_seoul[Popular_seoul['구별'].isnull()]

     구별  인구수  한국인  외국인  고령자
26  NaN  NaN  NaN  NaN  NaN

In [30]:
## missing value 제거
Popular_seoul.drop([26],inplace=True)
Popular_seoul.head()

    구별       인구수       한국인      외국인      고령자
1  종로구  162820.0  153589.0   9231.0  25425.0
2   중구  133240.0  124312.0   8928.0  20764.0
3  용산구  244203.0  229456.0  14747.0  36231.0
4  성동구  311244.0  303380.0   7864.0  39997.0
5  광진구  372164.0  357211.0  14953.0  42214.0

In [31]:
## 비율 정보 추가하기
Popular_seoul['외국인비율'] = Popular_seoul['외국인']/Popular_seoul['인구수']*100
Popular_seoul['고령자비율'] = Popular_seoul['고령자']/Popular_seoul['인구수']*100
Popular_seoul.head()

    구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
1  종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2   중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3  용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
4  성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
5  광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849

In [40]:
## 고령자 비율 가장 높은 top5출력
Popular_seoul.sort_values(by="고령자비율",ascending=False).head(5)

      구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806  16.600342
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221  14.720797

In [41]:
## 외국인 비율 가장 높은 top5출력
Popular_seoul.sort_values(by="외국인비율",ascending=False).head(5)

      구별       인구수       한국인      외국인      고령자     외국인비율      고령자비율
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598  13.006191
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998  12.689506
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427